#IMAGEN DE NODE.JS
FROM node:18-alpine

#ESTABLECE EL DIRECTORIO DE TRABAJO DENTRO DEL CONTENEDOR
WORKDIR /app

#INSTALAR DEPENDENCIAS (COPIA EL PACKAGE.JSON Y PACKAGE-LOCK.JSON)
COPY package*.json ./

#INSTALACION DE DEPENDENCIAS DEL PROYECTO
RUN npm install

#COPIAR EL RESTO DEL CODIGO
COPY . .

#PUERTO
EXPOSE 3000

#COMANDO PARA INICIAR LA APLICACION
CMD ["npm", "start"]